spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/gleodb}
    driverClassName: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:12345}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  thymeleaf:
    cache: false
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/resources/templates
    livereload:
      enabled: true
  servlet:
    multipart:
      max-file-size: 8MB
      max-request-size: 8MB
    session:
      timeout: 30d
      cookie:
        max-age: 30d
        http-only: true
        secure: false
  mvc:
    throw-exception-if-no-handler-found: true

server:
  port: 8080
  address: 0.0.0.0
  error:
    whitelabel:
      enabled: false

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

spring.h2.console.enabled: false